### ISSUE TITLE
Current Stoa is not compatible with current Agora

### ISSUE THREAD

**Issue by Geod24** [bosagora/stoa#234]
```
Dec 29 06:48:51 eu-002 docker[4638]: [Stoa] 2020-12-29T06:48:51.484Z info Connected to Agora, block height is 0
Dec 29 06:48:51 eu-002 docker[4638]: [Stoa] 2020-12-29T06:48:51.530Z error Failed to catch up to block height of Agora: Error: Validation failed: BlockHeader - should NOT have additional properties
Dec 29 06:48:51 eu-002 docker[4638]: [Stoa] 2020-12-29T06:48:51.603Z error An error occured while starting the server: Error: Validation failed: BlockHeader - should NOT have additional properties
Dec 29 06:48:51 eu-002 docker[4638]:     at Function.JSONValidator.isValidOtherwiseThrow (/stoa/bin/node_modules/boa-sdk-ts/src/modules/utils/JSONValidator.ts:288:23)
Dec 29 06:48:51 eu-002 docker[4638]:     at Function.BlockHeader.reviver (/stoa/bin/node_modules/boa-sdk-ts/src/modules/data/BlockHeader.ts:95:23)
Dec 29 06:48:51 eu-002 docker[4638]:     at Function.Block.reviver (/stoa/bin/node_modules/boa-sdk-ts/src/modules/data/Block.ts:80:25)
Dec 29 06:48:51 eu-002 docker[4638]:     at /stoa/bin/src/Stoa.ts:741:75
Dec 29 06:48:51 eu-002 docker[4638]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
Dec 29 06:48:51 eu-002 docker[4638]: npm ERR! code ELIFECYCLE
```

CC @MichaelKim20 @TrustHenry

**Comment by AndrejMitrovic** [comment]
There's two new fields in the block header. `random_seed` and `missing_validators` from [this PR](https://github.com/bpfkorea/agora/pull/1438/files#diff-bff84c529729a0f0270614e95926745f22c1311c963de83b850e4c4b6d08725a).

Apologies for not making an issue out of this sooner to prepare.

**Comment by ferencdg** [comment]
we have yet an additional field in the block header:     

/// Block unix timestamp
    public ulong timestamp;
