### ISSUE TITLE
Error processing transactions with multiple outputs.

### ISSUE THREAD

**Issue by MichaelKim20** [bosagora/stoa#410]
Transaction
```
{
  "inputs": [
    {
      "utxo": "0xcbd74f6de5052f6a8fe75a9254acc81d415e231dc1ee3b134ef6fcb7683920fd625a2bdbe8f976f1d9e499243b3e5984a2994b262466fc054ffdcb8f25fd4cb7",
      "unlock": {
        "bytes": "7Y4sY+OYhCpfXY9UqeVOjJF9qRfMOagFdEYMzOvImgpEGR46oKR1nbK8XTUd7by/0GifZmVUAg5pCPPosKnyGQ=="
      },
      "unlock_age": 0
    }
  ],
  "outputs": [
    {
      "type": 0,
      "value": "50833333276",
      "lock": {
        "type": 0,
        "bytes": "Ate+LNLJUx+o7RWQyciyfSbWatejhIYwanyBJ7dDOu8="
      }
    },
    {
      "type": 0,
      "value": "50833333276",
      "lock": {
        "type": 0,
        "bytes": "DDe9eGdfQinfnGonyPxv2eXvlwrwaqpInOg9vgJXTkI="
      }
    },
    {
      "type": 0,
      "value": "50833333276",
      "lock": {
        "type": 0,
        "bytes": "EYe/JphhpyfrfzNGSTGjyi9oh3TqASbRBD0+1LQGp30="
      }
    },
    {
      "type": 0,
      "value": "50833333276",
      "lock": {
        "type": 0,
        "bytes": "Jhe/Ws8PvV0hU8+BS0Q2qQsNbe+AlV28mp1zTpK4IGU="
      }
    },
    {
      "type": 0,
      "value": "7963888753064",
      "lock": {
        "type": 0,
        "bytes": "OGe8GW/cId6i2K9waXwpjtqgmSxL9B7B3aIUI6aZhfo="
      }
    },
    {
      "type": 0,
      "value": "50833333276",
      "lock": {
        "type": 0,
        "bytes": "Uje+l+tyLswbFmKSlguLKzOCIuP+MUMRXXbMS8mY5+g="
      }
    },
    {
      "type": 0,
      "value": "50833333276",
      "lock": {
        "type": 0,
        "bytes": "WYe93zTW143m+Ag9TQyeESjfhi23DWYctRJ7FTf49Xc="
      }
    },
    {
      "type": 0,
      "value": "50833333276",
      "lock": {
        "type": 0,
        "bytes": "cLe8l6MlDbuvCUxs8z7yhWkbtJHl+u0FJSRlZIK2udw="
      }
    },
    {
      "type": 0,
      "value": "50833333276",
      "lock": {
        "type": 0,
        "bytes": "u4e/HutsOceQXuaMXRlArj9WSkrHbWiqDTK4xapkTTc="
      }
    },
    {
      "type": 0,
      "value": "50833333276",
      "lock": {
        "type": 0,
        "bytes": "vje8d6Wk7NUOjxOOnzgwfWlZU7Uyl4I/DXwpiihr3Y0="
      }
    },
    {
      "type": 0,
      "value": "50833333285",
      "lock": {
        "type": 0,
        "bytes": "+oe+/SY6hOYzOPL/hMLHd9rt81bxuqJiNkrWk4J47Xc="
      }
    }
  ],
  "payload": "",
  "lock_height": "0"
}
```

Log
```
stoa_1   | (node:25) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 93)
stoa_1   | (node:25) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'address' of undefined
stoa_1   |     at /stoa/bin/src/modules/storage/LedgerStorage.ts:968:63
stoa_1   |     at runMicrotasks (<anonymous>)
stoa_1   |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
stoa_1   | (node:25) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections
```

**Comment by MichaelKim20** [comment]
I printed out the log and the senders [sender_index] were undefined.
