### ISSUE TITLE
Intermittent errors occur in CI tests.

### ISSUE THREAD

**Issue by TrustHenry** [bosagora/stoa#427]
```
  1) Test of the path /utxo
       Test of the path /wallet/balance no pending transaction :

      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

  {
    address: 'boa1xparc00qvv984ck00trwmfxuvqmmlwsxwzf3al0tsq5k2rw6aw427ct37mj',
+   balance: '0',
-   balance: '24399999990480',
    frozen: '0',
    locked: '0',
+   spendable: '0'
-   spendable: '24399999990480'
  }
      + expected - actual

       {
         "address": "boa1xparc00qvv984ck00trwmfxuvqmmlwsxwzf3al0tsq5k2rw6aw427ct37mj"
      -  "balance": "0"
      +  "balance": "24399999990480"
         "frozen": "0"
         "locked": "0"
      -  "spendable": "0"
      +  "spendable": "24399999990480"
       }
      
      at Context.<anonymous> (tests\Stoa.test.ts:749:16)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:94:5)

  2) Test of the path /utxo
       Test of the path /utxo no pending transaction :

      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

+ []
- [
-   {
-     amount: '24399999990480',
-     height: '1',
-     lock_bytes: 'ejw94GMKeuLPesbtpNxgN7+6BnCTHv3rgCllDdrrqq8=',
-     lock_type: 0,
-     time: 1609459800,
-     type: 0,
-     unlock_height: '2',
-     utxo: '0x6c985ecd25f0dbfd201bc73b6c994c7ac40bcaf7506712afbcc25ebbb1a00435440868c4943c8b851ffb9401d192d27ca9473627972401508e0b022047bd88b6'
-   }
- ]
      + expected - actual

      -[]
      +[
      +  {
      +    "amount": "24399999990480"
      +    "height": "1"
      +    "lock_bytes": "ejw94GMKeuLPesbtpNxgN7+6BnCTHv3rgCllDdrrqq8="
      +    "lock_type": 0
      +    "time": 1609459800
      +    "type": 0
      +    "unlock_height": "2"
      +    "utxo": "0x6c985ecd25f0dbfd201bc73b6c994c7ac40bcaf7506712afbcc25ebbb1a00435440868c4943c8b851ffb9401d192d27ca9473627972401508e0b022047bd88b6"
      +  }
      +]
      
      at Context.<anonymous> (tests\Stoa.test.ts:771:16)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:94:5)

```

These are error messages.

**Comment by MichaelKim20** [comment]
```
Run ankane/setup-mysql@v1
curl -Ls -o mysql.zip https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.22-winx64.zip
child_process.js:660
    throw err;
    ^

Error: Command failed: curl -Ls -o mysql.zip https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.22-winx64.zip
    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at run (D:\a\_actions\ankane\setup-mysql\v1\index.js:12:3)
    at Object.<anonymous> (D:\a\_actions\ankane\setup-mysql\v1\index.js:72:3)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  status: 35,
  signal: null,
  output: [ null, null, null ],
  pid: 2796,
  stdout: null,
  stderr: null
}
```

**Comment by TrustHenry** [comment]
https://github.com/bosagora/stoa/pull/426
Resolved in this PR.
